### ISSUE TITLE
(optional) introduce Pingouin for stats

### ISSUE THREAD

**Issue by xinmingxu** [ContextLab/cs-for-psych#1]
[Pingouin](https://pingouin-stats.org/) is an open-source statistical package written in Python 3 and based mostly on Pandas and NumPy. I haven't tried it myself but it seems well suited for most basic statistical tests.

**Comment by jeremymanning** [comment]
thanks @xinmingxu -- i've added a link to pingouin to [module 6](https://github.com/ContextLab/cs-for-psych/tree/master/slides#module-6-interrogating-your-data)!
